import Link from "next/link";

import sb from "../../../../public/sb.png";
import { FaFacebookF, FaTwitter, FaInstagram, FaLinkedinIn } from "react-icons/fa";

import "./Footer.scss";
import Image from "next/image";

export default function Footer() {
    return (
        <footer className="footer">
            <div className="footer-container">
                <div className="footer-section">
                    <h2>Something Broadband</h2>
                    <Image className="footer-logo" src={sb} alt="logo" />
                </div>
                <div className="footer-section">
                    <h3 className="footer-title">Quick Links</h3>
                    <ul className="footer-list">
                        <li>
                            <Link href="/about">About</Link>
                        </li>
                        <li>
                            <Link href="/iplans">Internet Plans</Link>
                        </li>
                        <li>
                            <Link href="/tvplans">TV Plans</Link>
                        </li>
                        <li>
                            <Link href="/contact">Contact Us</Link>
                        </li>
                    </ul>
                </div>
                <div className="footer-section">
                    <h3 className="footer-title">Customer Support</h3>

                    <ul className="footer-list">
                        <li>
                            <Link href="/faq">FAQ</Link>
                        </li>
                        <li>
                            <Link href="/help">Help Center</Link>
                        </li>
                        <li>
                            <Link href="/terms">Terms and Conditions</Link>
                        </li>
                        <li>
                            <Link href="/privacy">Privacy Policy</Link>
                        </li>
                    </ul>
                </div>
                <div className="footer-section">
                    <h3 className="footer-title">Follow Us</h3>

                    <ul className="footer-social">
                        <li>
                            {" "}
                            <Link href="https://facebook.com">
                                <FaFacebookF />
                            </Link>
                        </li>
                        <li>
                            <Link href="https://twitter.com">
                                <FaTwitter />
                            </Link>
                        </li>
                        <li>
                            <Link href="https://instagram.com">
                                <FaInstagram />
                            </Link>
                        </li>
                        <li>
                            <Link href="https://linkedin.com">
                                <FaLinkedinIn />
                            </Link>
                        </li>
                    </ul>
                </div>
            </div>
            <div className="footer-bottom">
                <p>&copy; 2024 Most of text here are generated by chat-GPT.</p>
            </div>
        </footer>
    );
}
