import ClientWrapper from "./components/ClientComponent/ClientComponent";
import Footer from "./components/Footer/Footer";
import Navigation from "./components/Navigation/Navigation";
import { AuthProvider } from "@/context/AuthContext";
import "./globals.css";
import { ContentProvider } from "@/context/ContentContext";

export const metadata = {
    title: "Something Broadband",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <ClientWrapper>
                    <AuthProvider>
                        <ContentProvider>
                            <Navigation />
                            {children}
                            <Footer />
                        </ContentProvider>
                    </AuthProvider>
                </ClientWrapper>
            </body>
        </html>
    );
}
